// Source of truth for the Supabase project the site talks to.
//
// This intentionally overrides utils/supabase/info.tsx: that file is autogenerated
// by the Figma Make connection and keeps pointing at the Make-managed project
// (ywlvqxhjzkqrqnzkjbfq). The real edge functions and data live in the owner's
// self-managed project (enwbfsbcxoqqnbkrngyb), so the app reads its config here
// instead — a file Make does not regenerate.
//
// publicAnonKey is a PUBLIC key (shipped in the browser bundle). Never put the
// service_role / secret key here.

export const projectId = "enwbfsbcxoqqnbkrngyb"
export const publicAnonKey = "sb_publishable_hlRvsVjBfiow-U4xA7FTrQ_JuamG6qV"
