/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ywlvqxhjzkqrqnzkjbfq"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3bHZxeGhqemtxcnFuemtqYmZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg1NjYwNDUsImV4cCI6MjEwNDE0MjA0NX0.gvdTaRd6nz5ZgxqOEg8H78im1eX0MlUD-Vy58U-z7m8"